name: wassistant
description: An unofficial World of Warships assistant App.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  bloc: ^3.0.0
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  dio: ^3.0.9
  equatable: ^1.1.1
  extended_nested_scroll_view: ^0.4.0
  fimber: ^0.4.0
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  fluro: ^1.6.1
  flutter_bloc: ^3.2.0
  flutter_launcher_icons: ^0.7.4
  flutter_screenutil: ^1.1.0
  get_it: ^4.0.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  oktoast: ^2.3.1+1
  package_info: ^0.4.0+16
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  intl_translation: ^0.17.9
  json_serializable: ^3.2.5
  mockito: ^4.1.1
  pedantic: ^1.8.0+1

dependency_overrides:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
   - images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
