name: wassistant
description: An unofficial World of Warships assistant App.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^4.0.0
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  dio: ^3.0.9
  extended_nested_scroll_view: ^0.4.0
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  fluro: ^1.6.3
  flutter_bloc: ^4.0.0
  flutter_launcher_icons: ^0.7.5
  flutter_screenutil: ^1.1.0
  freezed_annotation: ^0.7.1
  get_it: ^4.0.2
  injectable: ^0.3.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  logger: ^0.9.1
  oktoast: ^2.3.2
  package_info: ^0.4.0+17
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.7+1
  styled_widget: ^0.2.1+2
  time: ^1.3.0
  url_launcher: ^5.4.5
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0
  freezed: ^0.10.8
  injectable_generator: ^0.3.5
  intl_translation: ^0.17.9
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
   - images/
